config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :labels
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:show]

  resources :targets do
    member do
      post "achieve"
    end
  end

  resources :labels do
    get "targets", to: "targets#search"
  end
  
  root to: "targets#index"
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user
  has_many :target_labels, dependent: :destroy
  has_many :labels, through: :target_labels
  validates :title, presence: true, length: { in: 1..50 }
  validates :detail, length: { maximum: 1000 }
  validates :deadline, presence: true
  validate :date_before_start

  def date_before_start
    if deadline.nil? || deadline < DateTime.now
      errors.add(:deadline, "は今日以降のものを選択してください")
    end
  end

  def save_label(sent_labels)
    current_labels = self.labels.pluck(:name) unless self.labels.nil?
    old_labels = current_labels - sent_labels
    new_labels = sent_labels - current_labels

    old_labels.each do |old|
      self.labels.delete Label.find_by(name: old)
    end

    new_labels.each do |new|
      new_target_label = Label.find_or_create_by(name: new)
      self.labels << new_target_label
    end
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: %i[ show edit update destroy achieve]
  before_action :authenticate_user!

  def index
    @label_list = Label.all
    if @q_label
      @targets = @q_label.joins(:targets).eager_load(:targets).where(user_id: current_user.id)
    else
      @q = Target.ransack(params[:q])
      @targets = @q.result(distinct: true).where(user_id: current_user.id)
    end
  end

  def show
    @target = Target.find(params[:id])
    @target_labels = @target.labels
  end

  def new
    @target = current_user.targets.build
  end

  def create
    @target = current_user.targets.build(target_params)
    label_list = params[:target][:name].split(nil)
    if params[:back]
      render :new
    else
      if @target.save
        @target.save_label(label_list)
        redirect_to targets_path, notice: "ターゲットを作成しました！"
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    label_list = params[:target][:name].split(nil)
    if @target.update(target_params)
      @target.save_label(label_list)
      redirect_to targets_path, notice: "ターゲットを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @target.destroy
    redirect_to targets_path, notice: "ターゲットを削除しました！"
  end

  def achieve
    @target.update status: true
    redirect_to targets_path, notice: "#{@target.title}を達成しました！おめでとう！！"
  end

  private
  def set_target
    @target = Target.find(params[:id])
  end

  def target_params
    params.require(:target).permit(:title, :detail, :deadline, label_ids: [])
  end

  def set_q_for_label
    @q_label = Target.ransack(params[:q])
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<div class="box">
  <div class="form-group">
      <%= form_with(model: @target, local: true) do |f| %>
        <% if @target.errors.any? %>
        <div id="error_explanation">
            <h2><%= @target.errors.count %>件のエラーがあります。</h2>
            <ul>
                <% @target.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>
        <div class="target_label">
              <%= f.label :Label %>
              <%= f.text_field :name, placeholder: "Let's label your targets!", class: "form-control" %>
        </div>
        <div class="target_title">
            <%= f.label :Title %>
            <%= f.text_field :title, placeholder: "What is your target?", class: "form-control" %>
        </div>
        <div class="target_detail">
            <%= f.label :Detail %>
            <%= f.text_area :detail, placeholder: "Detail of your target", class: "form-control" %>
        </div>
        <div class="target_deadline">
            <%= f.label :Deadline %>
            <%= f.datetime_field :deadline, class: "form-control" %>
        </div>
        <% if current_page?(new_target_path) %>
          <%= f.submit "Create", class: "btn  btn-default" %>
        <% else %>
          <%= f.submit "Update", class: "btn  btn-default" %>
        <% end %>
      <% end %>
    <%= link_to "HOME", targets_path %>
  </div>
</div>

app/views/targets/edit.html.erb
<h2 class="head_title">Edit Target</h2>
<%= render 'form' %>

app/views/targets/index.html.erb
<h2 class="head_title">Targets List</h2>
<%= link_to "Create new Target", new_target_path, class: 'btn btn-primary center-block' %>

<div class="form-inline">
    <%= search_form_for @q do |f| %>
    <div class="form-group">
        <%= f.label :title, "Keyword", class: "" %>
        <%= f.search_field :title_cont %>
    </div>
    <div class="form-group">
        <%= f.label :status %>
        <%= f.radio_button :status_eq, '', {:checked => true} %>指定なし
        <%= f.radio_button :status_eq, false %>未達成
        <%= f.radio_button :status_eq, true %>完了
    </div>
    <%= f.submit "Search" %>
    <% end %>
    <br>
    <div class="label_list">
      <% @label_list.each do |l| %>
        <%= link_to l.name, targets_path(@q_label, {q:{ name_eq: l.name }}) %>
        <%= "(#{l.targets.count})" %>
      <% end %>
    </div>
    <div class="sort_link">
        <%= sort_link(@q, :deadline, "Sort as Deadline", ontouchstart="") %>
    </div>
</div>

<div class="targets_content">
    <% @targets.each do |t| %>
    <div class="target_block">
        <div class="labelling">
          <p>
            <% t.labels.each do |l| %>
              <%= l.name %>
            <% end %>
          </p>
        </div>
        <p id="target_title"><strong><%= t.title %></strong></p>
        <div>
          <% if t.status == true %>
          <p class="achieve_message">達成してるよ!</p>
          <% else %>
          <%= button_to "達成！", achieve_target_path(t.id), method: :POST, data: { confirm: "達成済みにしますか？一度押すと戻せないよ！" }, class: "btn btn-danger" %>
          <% end %>
        </div>
        <p><strong><%= t.deadline.strftime("%Y %m/%d") %></strong></p>
        <p>
            <% if t.status == true %>
            <%= link_to 'Show', target_path(t) %>
            <% else %>
            <%= link_to 'Show', target_path(t) %>
            <%= link_to 'Edit', edit_target_path(t) %>
            <%= link_to 'Destroy', target_path(t), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </p>
    </div>
    <% end %>
</div>

app/views/targets/new.html.erb
<h2 class="head_title">Create New Target</h2>
<%= render 'form' %>

app/views/targets/show.html.erb
<h2 class="head_title">Deatil of Target</h2>
<div class="box">
    <div class="box-show">
        <p>
            <% @target.labels.each do |l| %>
                <%= l.name %>
            <% end %>
        </p>
        <p class="target_title">
            <strong>Title:</strong>
            <%= @target.title %>
        </p>
        <p class="target_detail">
            <strong>Detail:</strong>
            <%= @target.detail %>
        </p>
        <p class="target_deadline">
            <strong>Deadline:</strong>
            <%= @target.deadline.strftime("%Y-%m-%d %H:%M") %>
        </p>
        <div class="achieve">
            <% if @target.status == true %>
            <p class="achieve_message">達成してるよ!</p>
            <% else %>
            <%= button_to "達成！", achieve_target_path(@target), method: :POST, data: { confirm: "達成済みにしますか？一度押すと戻せないよ！" }, class: "btn btn-danger"%>
            <% end %>
        </div>
        <br>
        <% if @target.status == false %>
        <%= link_to 'Edit', edit_target_path(@target) %>
        <% end %>
        <br>
        <%= link_to 'HOME', targets_path %>
    </div>
</div>