config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :labels
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:show]

  resources :targets do
    member do
      post "achieve"
    end
  end

  resources :labels do
    get "targets", to: "targets#search"
  end
  
  root to: "targets#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>ShooTargets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <header class="header">
        <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
        <label for="openSidebarMenu" class="sidebarIconToggle">
            <div class="spinner diagonal part-1"></div>
            <div class="spinner horizontal"></div>
            <div class="spinner diagonal part-2"></div>
        </label>
        <div id="sidebarMenu">
            <ul class="sidebarMenuInner">
                <% if user_signed_in? %>
                <li><%= current_user.name %></li>
                <li><%= link_to "MY PAGE", user_path(current_user.id) %></li>
                <li><%= link_to "HOME", targets_path %></li>
                <li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
                <% else %>
                <li><%= link_to "SIGN UP", new_user_registration_path %></li>
                <li><%= link_to "LOGIN", new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </header>
    <div class="logo">
        <img src="/assets/shootargets.png" alt="ShooTargets logo">
    </div>
    <div class="content">
        <div class="notification">
            <% if notice %>
            <p class="alert alert-info"><%= notice %></p>
            <% end %>
            <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
            <% end %>
        </div>
        <%= yield %>
    </div>
    <footer class="footer">
        <p>Copyright © 2020 faye0210 ALL RIGHTS RESERVED.</p>
    </footer>
</body>

</html>